VWC_L_Flag_hr(isnan(VWC_L_Flag_hr))=1;
VWC_E_Flag_hr(isnan(VWC_E_Flag_hr))=1;

sflag = char([
    num2str(VWC_L_Flag_hr(:,3,1,2)) num2str(VWC_L_Flag_hr(:,3,1,3)) num2str(VWC_L_Flag_hr(:,3,1,4)) num2str(VWC_L_Flag_hr(:,3,1,5)) ...
    num2str(VWC_L_Flag_hr(:,3,2,2)) num2str(VWC_L_Flag_hr(:,3,2,3)) num2str(VWC_L_Flag_hr(:,3,2,4)) num2str(VWC_L_Flag_hr(:,3,2,5)) ...
    num2str(VWC_L_Flag_hr(:,3,3,2)) num2str(VWC_L_Flag_hr(:,3,3,3)) num2str(VWC_L_Flag_hr(:,3,3,4)) num2str(VWC_L_Flag_hr(:,3,3,5)) ...
    num2str(VWC_L_Flag_hr(:,3,4,2)) num2str(VWC_L_Flag_hr(:,3,4,3)) num2str(VWC_L_Flag_hr(:,3,4,4)) num2str(VWC_L_Flag_hr(:,3,4,5)) ...
    %num2str(VWC_E_Flag_hr(:,2,1,2)) num2str(VWC_E_Flag_hr(:,2,1,3)) num2str(VWC_E_Flag_hr(:,2,1,4)) num2str(VWC_E_Flag_hr(:,2,1,5)) ...
    %num2str(VWC_E_Flag_hr(:,2,2,2)) num2str(VWC_E_Flag_hr(:,2,2,3)) num2str(VWC_E_Flag_hr(:,2,2,4)) num2str(VWC_E_Flag_hr(:,2,2,5)) ...
    %num2str(VWC_E_Flag_hr(:,2,3,2)) num2str(VWC_E_Flag_hr(:,2,3,3)) num2str(VWC_E_Flag_hr(:,2,3,4)) num2str(VWC_E_Flag_hr(:,2,3,5)) ...
    %num2str(VWC_E_Flag_hr(:,2,4,2)) num2str(VWC_E_Flag_hr(:,2,4,3)) num2str(VWC_E_Flag_hr(:,2,4,4)) num2str(VWC_E_Flag_hr(:,2,4,5)) ...
    %num2str(Wd_hr_flag(:,2,1,1)) num2str(Wd_hr_flag(:,2,1,1)) num2str(Wd_hr_flag(:,3,1,1)) num2str(Wd_hr_flag(:,4,1,1))...
    %num2str(Ws_hr_flag(:,2,1,1)) num2str(Ws_hr_flag(:,2,1,1)) num2str(Ws_hr_flag(:,3,1,1)) num2str(Ws_hr_flag(:,4,1,1))...
    %num2str(Tair_hr_flag(:,2,1,1)) num2str(Tair_hr_flag(:,2,1,1)) num2str(Tair_hr_flag(:,3,1,1)) num2str(Tair_hr_flag(:,4,1,1))
             %num2str(flag_c(:,2)) num2str(flag_GC(:,2)) num2str(flag_out2(:,2)) num2str(flag_out(:,2)) ...
             %num2str(flag_c(:,3)) num2str(flag_GC(:,3)) num2str(flag_out2(:,3)) num2str(flag_out(:,3)) ...
             ]);
%sflag(isnan(sflag))=1;
ssflag = bin2dec(sflag);

out_file = sprintf('%s.dat' ,'CR300_19_Soil_flagged');
    fid = fopen(sprintf('%s', out_file),'wt');
    fprintf(fid, '%s.dat, %s factory calibration \n', 'CR300_19_Soil', 'version 1');
    fprintf(fid, 'Date,              Ppt,  VWC_5, VWC_10, VWC_20, VWC_50,    T_5,   T_10,   T_20,   T_50,     Flag\n');
    for j = 1:length(tS_hr)
        fprintf(fid, '%s, %6.2f, %6.3f, %6.3f, %6.3f, %6.3f, %6.2f, %6.2f, %6.2f, %6.2f, %8i\n', datestr(tS_hr(j),'mm-dd-yyyy HH:MM:SS'), PPT_hr(j,3),...
            VWC_hr(j,1,3,1), VWC_hr(j,2,3,1), VWC_hr(j,3,3,1),VWC_hr(j,4,3,1),T_hr(j,1,3,1), T_hr(j,2,3,1), ...
            T_hr(j,3,3,1),T_hr(j,4,3,1), ssflag(j));
    end
    fclose(fid);
    
    
   sflagw=char([
       num2str(Ws_hr_flag(:,3,1)) num2str(Ws_hr_flag(:,3,2)) num2str(Ws_hr_flag(:,3,3)) num2str(Ws_hr_flag(:,3,5))...
       num2str(Wd_hr_flag(:,3,1)) num2str(Wd_hr_flag(:,3,2)) num2str(Wd_hr_flag(:,3,3)) num2str(Wd_hr_flag(:,3,4))...
       num2str(Tair_hr_flag(:,3,1)) num2str(Tair_hr_flag(:,3,2)) num2str(Tair_hr_flag(:,3,3)) num2str(Tair_hr_flag(:,3,5))...
       num2str(Tdew_hr_flag(:,3,1)) num2str(Tdew_hr_flag(:,3,2)) num2str(Tdew_hr_flag(:,3,3)) num2str(Tdew_hr_flag(:,3,5))...
       num2str(Srad_hr_flag(:,3,1)) num2str(Srad_hr_flag(:,3,2))
       ]);
   
   ssflagw = bin2dec(sflagw);
   
out_file = sprintf('%s.dat' ,'CR300_19_Meteoro_flagged');
    fid = fopen(sprintf('%s', out_file),'wt');
    fprintf(fid, '%s.dat, %s factory calibration \n', 'CR300_19_Meteorological', 'version 1');
    fprintf(fid, 'Date,              Ppt,  Wind_speed, Wind_direction, T_air, T_dew, Solar_radiation  Flag\n');
    for j = 1:length(tS_hr)
        fprintf(fid, '%s, %6.2f, %6.3f, %6.3f, %6.2f, %6.2f, %6.2f, %8i\n', datestr(tS_hr(j),'mm-dd-yyyy HH:MM:SS'), PPT_hr(j,3),...
            Ws_hr(j,3), Wd_hr(j,3), Tair_hr(j,3),Tdew_hr(j,3),Srad_hr(j,3), ssflagw(j));
    end
    fclose(fid);   
   
   
